spring:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20
    generate-ddl: true
    defer-datasource-initialization: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:alenkin
    #    tcp: jdbc:h2:tcp://localhost:9092/mem:alenkin
    username: sa
    password:
  h2.console.enabled: true
  data:
    rest:
      base-path: /api
      return-body-on-create: true
      default-page-size: 20

logging:
  level:
    root: warn
    edu.alenkin: debug
    org.springframework.security.web.FilterChainProxy: DEBUG
server.servlet:
  encoding:
    charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
    enabled: true # Enable http encoding support
    force: true